# Generated by Django 5.2.10 on 2026-01-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Icerik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazi', models.TextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='resimler/')),
                ('tur', models.CharField(choices=[('haber', 'Haber / Blog Yazısı'), ('soru', 'Forum Sorusu')], default='haber', max_length=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kategori')),
            ],
        ),
    ]
