# Generated by Django 5.2.10 on 2026-01-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yanitlar', to='posts.yorum'),
        ),
    ]
