# Generated by Django 5.2.10 on 2026-01-30 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_yorum_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='begenenler',
            field=models.ManyToManyField(blank=True, related_name='begendigi_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
