# Generated by Django 5.2.10 on 2026-01-30 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_yorum_begenenler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icerik',
            name='kaydedenler',
            field=models.ManyToManyField(blank=True, related_name='kaydedilen_icerikler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icerik',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='icerik_resimleri/'),
        ),
    ]
