# Generated by Django 5.2.11 on 2026-02-07 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_icerik_kaydedenler_alter_icerik_resim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukAktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('sure_dk', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_aktiviteler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Günlük Aktiviteler',
                'unique_together': {('user', 'tarih')},
            },
        ),
    ]
