# Generated by Django 5.2.11 on 2026-02-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_gunlukaktivite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('icerik', 'İçerik Paylaşımı'), ('yorum', 'Yorum Yapma'), ('begeni', 'Yorum Beğenme'), ('kayit', 'İçerik Kaydetme'), ('rozet', 'Rozet Kazanma')], max_length=10)),
                ('detay', models.CharField(blank=True, max_length=255)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazdigi_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gunlukaktivite',
            index=models.Index(fields=['user', 'tarih'], name='posts_gunlu_user_id_3aec09_idx'),
        ),
        migrations.AddIndex(
            model_name='gunlukaktivite',
            index=models.Index(fields=['tarih'], name='posts_gunlu_tarih_ca1033_idx'),
        ),
        migrations.AddField(
            model_name='aktivite',
            name='icerik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.icerik'),
        ),
        migrations.AddField(
            model_name='aktivite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktiviteler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aktivite',
            name='yorum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.yorum'),
        ),
    ]
