# Generated by Django 5.2.11 on 2026-02-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_aktivite_alter_profil_user_alter_yorum_yazar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='timeout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
