# Generated by Django 5.2.12 on 2026-03-03 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_yorum_depth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gunlukaktivite",
            name="tarih",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
