# Generated by Django 6.0.3 on 2026-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_profil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='boy',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Boy (cm)'),
        ),
        migrations.AddField(
            model_name='profil',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='profil',
            name='fitness_hedefi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Fitness Hedefi'),
        ),
        migrations.AddField(
            model_name='profil',
            name='hedef_kilo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hedef Kilo (kg)'),
        ),
        migrations.AddField(
            model_name='profil',
            name='kilo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Kilo (kg)'),
        ),
    ]
