# Generated by Django 6.0.3 on 2026-05-18 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_icerik_begenenler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukBeslenmeSu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('su_ml', models.IntegerField(default=0)),
                ('kalori_kcal', models.IntegerField(default=0)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('karbonhidrat_g', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('yag_g', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beslenme_su_kayitlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Günlük Beslenme ve Su Kayıtları',
                'db_table': 'posts_gunlukbeslenmesu',
                'unique_together': {('user', 'tarih')},
            },
        ),
    ]
