# Generated by Django 6.0.3 on 2026-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_profil_gunluk_su_hedefi_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='baslangic_kilo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hedef İçin Başlangıç Kilosu (kg)'),
        ),
    ]
