# Generated by Django 6.0.3 on 2026-05-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_profil_baslangic_kilo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mobil OAuth Kodu')),
                ('state', models.CharField(db_index=True, max_length=128, verbose_name='Mobil OAuth State')),
                ('code_challenge', models.CharField(max_length=128, verbose_name='PKCE Code Challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_oauth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobil OAuth Kodu',
                'verbose_name_plural': 'Mobil OAuth Kodları',
                'indexes': [models.Index(fields=['created_at'], name='posts_mobileoauth_created_idx'), models.Index(fields=['user', 'state'], name='posts_moauth_user_state_idx')],
            },
        ),
    ]
