# Generated by Django 6.0.3 on 2026-05-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_turkce_yardimci_tablo_adlari'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gunlukaktivite',
            new_name='gunluk_akti_user_id_c5f481_idx',
            old_name='posts_gunlu_user_id_3aec09_idx',
        ),
        migrations.RenameIndex(
            model_name='gunlukaktivite',
            new_name='gunluk_akti_tarih_2b5644_idx',
            old_name='posts_gunlu_tarih_ca1033_idx',
        ),
    ]
