# Generated by Django 5.2.12 on 2026-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        unique=True, verbose_name="Yasaklı IP Adresi"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Yasaklanma Nedeni",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yasaklanma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yasaklı IP",
                "verbose_name_plural": "Yasaklı IP'ler",
                "ordering": ["-created_at"],
            },
        ),
    ]
