"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# .env dosyasını oku
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DEBUG', 'False').lower() == 'true':
        SECRET_KEY = 'django-insecure-dev-only-key-change-in-production'
    else:
        raise ValueError('SECRET_KEY environment variable is required in production!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'



ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['*'] if DEBUG else ['fitrehber.com.tr', 'www.fitrehber.com.tr']


# Reverse proxy güven ayarları
TRUST_PROXY_HEADERS = os.environ.get('TRUST_PROXY_HEADERS', 'False') == 'True'
TRUSTED_PROXY_IPS = [ip.strip() for ip in os.environ.get('TRUSTED_PROXY_IPS', '').split(',') if ip.strip()]

# HTTPS/CSRF Ayarları (Django 4.0+ için şart)
CSRF_TRUSTED_ORIGINS = [
    'https://fitrehber.com.tr',
    'https://www.fitrehber.com.tr',
    'https://localhost',
    'http://localhost',
    'https://127.0.0.1',
    'http://127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'core.apps.CoreConfig',
    'posts',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# AllAuth Settings
LOGIN_URL = '/giris/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'

# AllAuth Account Configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_ADAPTER = 'core.adapters.MyAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'core.adapters.MySocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.RateLimitMiddleware',
    'posts.middleware.BanCheckMiddleware',
    'posts.middleware.OnboardingRedirectMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'posts' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.app_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # BURASI DEĞİŞTİ
        'NAME': os.environ.get('DB_NAME', 'fityasam_db'),
        'USER': os.environ.get('DB_USER', 'nyancat'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'gizlisifre'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '3306'), # MySQL Portu
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4', # Türkçe karakterler ve emojiler için kritik
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'posts' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Yüklenen dosyaların tarayıcıdaki adresi (Örn: localhost:8000/media/resim.jpg)
MEDIA_URL = '/media/'

# Dosyaların bilgisayarda saklanacağı fiziksel klasör
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== SEO SETTINGS ====================
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'https://fitrehber.com.tr').rstrip('/')
SITE_NAME = 'FitRehber'
SITE_ALTERNATE_NAME = 'Fit Rehber'
DEFAULT_SEO_TITLE = 'FitRehber | Bilimsel Fitness, Beslenme ve Supplement Rehberi'
DEFAULT_SEO_DESCRIPTION = (
    'FitRehber; bilimsel antrenman, beslenme, supplement ve sağlıklı yaşam '
    'konularında pratik rehberler, makaleler ve topluluk soruları sunar.'
)

# ==================== RESEND E-POSTA AYARLARI ====================
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'FitRehber <onboarding@resend.dev>')

# Free Tier Limitleri (güvenlik için)
RESEND_DAILY_LIMIT = 100     # Günlük max e-posta
RESEND_MONTHLY_LIMIT = 3000  # Aylık max e-posta

# E-posta Backend Seçimi
if DEBUG:
    EMAIL_BACKEND = 'core.email_backend.BrowserConsoleBackend'
else:
    EMAIL_BACKEND = 'core.email_backend.ResendEmailBackend'

# Production Security Settings (DEBUG=False olunca aktif)
if not DEBUG:
    # Proxy arkasındaysa HTTPS yönlendirmesi için gerekli:
    if TRUST_PROXY_HEADERS:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# ==================== PASSWORD RESET SETTINGS ====================
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours (in seconds)

# ==================== RATE LIMIT CACHE (ZORUNLU!) ====================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'rate_limit_cache_table',
    }
}

# --- RATE LIMIT AYARLARI ---
RATELIMIT_CACHE_PREFIX = "rate_limit_v2"
RATELIMIT_EXEMPT_PATHS = (
    "/static/",
    "/media/",
    "/admin/",
    "/aktivite-kaydet/",
    "/canli-arama/",
)
RATELIMIT_MANUAL_BAN_CACHE_TTL = 300

# Global koruma: normal gezinmeyi bozmaz, yoğun bot trafiğini geçici durdurur.
RATELIMIT_GLOBAL_WINDOW = 60
RATELIMIT_GLOBAL_AUTHENTICATED = 240
RATELIMIT_GLOBAL_ANONYMOUS = 120
RATELIMIT_GLOBAL_PENALTY = 60

# Yorum/cevap gönderimi izole edilir; diğer aksiyonları etkilemez.
RATELIMIT_COMMENT_MAX = 5
RATELIMIT_COMMENT_WINDOW = 60
RATELIMIT_COMMENT_PENALTY = 120

# Beğen/kaydet gibi kullanıcı aksiyonları.
RATELIMIT_REACTION_MAX = 20
RATELIMIT_REACTION_WINDOW = 30
RATELIMIT_REACTION_PENALTY = 20

# Canlı arama sessiz limitlenir; aşımda DB araması yapılmaz.
RATELIMIT_SEARCH_MAX = 20
RATELIMIT_SEARCH_WINDOW = 10

# ==================== MOBİL/WEB GOOGLE OAUTH ====================
# Flutter uygulamasının web sürümü Google ile giriş yaparken, OAuth dönüşü
# bu listedeki origin'lere yönlendirilebilir (open redirect koruması).
# localhost / 127.0.0.1 her zaman (port fark etmeksizin) izinlidir; geliştirme
# ortamı için ekleme gerekmez. Native uygulama deep link'i (fitrehber://) da
# her zaman izinlidir.
#
# Flutter web build'ini production'a deploy ettiğinde, barındırıldığı origin'i
# (scheme + host + port, sondaki / OLMADAN) buraya ekle. Örnek:
#   MOBILE_OAUTH_WEB_ORIGINS = ('https://app.fitrehber.com.tr',)
MOBILE_OAUTH_WEB_ORIGINS = ()
